services:
  crisalid-ikg:
    image: crisalidesr/crisalid-ikg:v0.18-dev
    container_name: crisalid-ikg
    ports:
      - 8001:8000
    environment:
      - APP_ENV=DEV
      - API_PREFIX=/api
      - API_VERSION=v1
      - AMQP_ENABLED=true
      - AMQP_HOST=crisalid-bus
      - AMQP_PORT=${CRISALID_BUS_AMQP_PORT}
      - AMQP_USER=${CRISALID_BUS_USER}
      - AMQP_PASSWORD=${CRISALID_BUS_PASSWORD}
      - NEO4J_URI=bolt://neo4j:${NEO4J_BOLT_PORT}
      - NEO4J_USER=
      - NEO4J_PASSWORD=
      - ES_ENABLED=false
      - ES_HOST=http://localhost
      - ES_PORT=9200
      - ES_USER=elastic
      - ES_PASSWORD=elastic
    depends_on:
      crisalid-bus:
        condition: service_healthy
      neo4j:
        condition: service_healthy
    command: bash -c "uvicorn app.main:app --host 0.0.0.0 --port 8000"
    profiles:
      - ikg